CALCULATE_REACTION_RATES – 3D-PDR
CALCULATE_REACTION_RATES Subroutine
248 statements
Source File
subroutine CALCULATE_REACTION_RATES(TEMPERATURE, DUST_TEMPERATURE, NRAYS, RAD_SURFACE, AV, COLUMN_NH2, COLUMN_NHD, COLUMN_NCO, COLUMN_NC, COLUMN_NS, NREAC, REACTANT, PRODUCT, ALPHA, BETA, GAMMA, rate, RTMIN, RTMAX, DUPLICATE, NSPEC, NRGR, NRH2, NRHD, NRCO, NRCI, NRSI, nelectron, density, ZETALOCAL)
Uses
healpix_types
maincode_module
global_module
definitions
functions_module
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: TEMPERATURE
real(kind=dp), intent(in) :: DUST_TEMPERATURE
integer(kind=i4b), intent(in) :: NRAYS
real(kind=dp), intent(in) :: RAD_SURFACE(0:nrays-1)
real(kind=dp), intent(in) :: AV(0:nrays-1)
real(kind=dp), intent(in) :: COLUMN_NH2(0:nrays-1)
real(kind=dp), intent(in) :: COLUMN_NHD(0:nrays-1)
real(kind=dp), intent(in) :: COLUMN_NCO(0:nrays-1)
real(kind=dp), intent(in) :: COLUMN_NC(0:nrays-1)
real(kind=dp), intent(in) :: COLUMN_NS(0:nrays-1)
integer(kind=i4b), intent(in) :: NREAC
character(len=10), intent(in) :: REACTANT(1:nreac,1:3)
character(len=10), intent(in) :: PRODUCT(1:nreac,1:4)
real(kind=dp), intent(in) :: ALPHA(1:nreac)
real(kind=dp), intent(in) :: BETA(1:nreac)
real(kind=dp), intent(in) :: GAMMA(1:nreac)
real(kind=dp), intent(out) :: rate(1:nreac)
real(kind=dp), intent(in) :: RTMIN(1:nreac)
real(kind=dp), intent(in) :: RTMAX(1:nreac)
integer(kind=i4b), intent(in) :: DUPLICATE(1:nreac)
integer(kind=i4b), intent(in) :: NSPEC
integer(kind=i4b), intent(out) :: NRGR
integer(kind=i4b), intent(out) :: NRH2
integer(kind=i4b), intent(out) :: NRHD
integer(kind=i4b), intent(out) :: NRCO
integer(kind=i4b), intent(out) :: NRCI
integer(kind=i4b), intent(out) :: NRSI
real(kind=dp), intent(in) :: nelectron
real(kind=dp), intent(in) :: density
real(kind=dp), intent(in) :: ZETALOCAL
Calls
Call graph
calculate_reaction_rates calls cipdrate, copdrate, h2pdrate, sipdrate