chemicaliterations – 3D-PDR
chemicaliterations Subroutine
23 statements
Source File
subroutine chemicaliterations(iw, ichem)
Uses
healpix_types
maincode_module
global_module
maincode_local
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: iw
integer, intent(in) :: ichem
Calls
Call graph
chemicaliterations calls calc_columndens, calculate_abundances, calculate_lte_populations, calculate_partition_function, calculate_reaction_rates