coolingfunctions – 3D-PDR
coolingfunctions Subroutine
39 statements
Source File
subroutine coolingfunctions()
Uses
healpix_types
m_Ray_box
maincode_module
global_module
Arguments
None
Calls
Call graph
coolingfunctions calls escape_probability, find_ccoeff, solvlevpop