evaluation_points – 3D-PDR
evaluation_points Subroutine
113 statements
Source File
subroutine evaluation_points()
Uses
healpix_types
maincode_module
m_Ray_box
healpix_module
definitions
m_Mesh
Arguments
None
Calls
Call graph
evaluation_points calls ang2pix_nest_id, heapsort, vec2ang