writeoutputs – 3D-PDR
writeoutputs Subroutine
177 statements
Source File
public subroutine writeoutputs()
Arguments
None
Calls
Called by
Call graph
writeoutputs calls h5close_f, h5dclose_f, h5dcreate_f, h5dwrite_f, h5fclose_f, h5fcreate_f, h5open_f, h5sclose_f, h5screate_simple_f, h5tcopy_f, h5tset_size_f, write_h5_one_r3d
write_h5_one_r3d calls h5dclose_f, h5dcreate_f, h5dwrite_f, h5sclose_f, h5screate_simple_f
convert_fin2h5 calls writeoutputs