write_h5_one_r3d – 3D-PDR
write_h5_one_r3d Subroutine
15 statements
Source File
public subroutine write_h5_one_r3d(file_id, dims, temp_real, name)
Arguments
Type Intent Optional Attributes Name
integer(kind=HID_T), intent(in) :: file_id
integer(kind=HSIZE_T), intent(in), dimension(3) :: dims
real(kind=RK), intent(in) :: temp_real(:,:,:)
character(len=*), intent(in) :: name
Calls
Called by
Call graph
write_h5_one_r3d calls h5dclose_f, h5dcreate_f, h5dwrite_f, h5sclose_f, h5screate_simple_f
writeoutputs calls write_h5_one_r3d
convert_fin2h5 calls writeoutputs