writeoutputs – 3D-PDR
writeoutputs Subroutine
230 statements
Source File
subroutine writeoutputs()
Uses
healpix_types
hdf5
maincode_module
global_module
Arguments
None
Calls
Call graph
writeoutputs calls h5dclose_f, h5dcreate_f, h5dwrite_f, h5fclose_f, h5fcreate_f, h5open_f, h5screate_simple_f, h5tcopy_f, h5tset_size_f